name 'gitrob'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures gitrob'
long_description 'Installs/Configures gitrob'
version '0.1.0'

depends 'apt'
depends 'postgresql'
depends 'database', '~>2.3.1'
